// const math=require("./math");
// const math2=require("./math2");
// const {add}=require("./math");
// console.log(math.add(1,2));
// console.log(math.multiply(2,3));
// console.log(math.subtract(2,3));
// console.log(math2.Add(1,3));
// console.log(add);
const math=require("./math");
console.log(math(1,2));